### ISSUE TITLE
[BUG] Small documentation Bug

### ISSUE THREAD

**Issue by MarcelGor** [hetida/hetida-designer#3]
Hi i think there is a small docu mistake at the part "Deployment of base component set into your installation"
You write "--entrypoint python hetida/runtime ..."
But i think it is "--entrypoint python  hetida/designer-runtime ..." or?

**Comment by stewit** [comment]
Yes you are right. Image names have changed and the Readme was not updated appropriately. We are going to correct this with the next release soon.
Thank you for bringing this to our attention!

**Comment by stewit** [comment]
This should is fixed with release 0.6.0. Thanks again!
