### ISSUE TITLE
[BUG] Port of hetida-designer-backend not exposed

### ISSUE THREAD

**Issue by brean** [hetida/hetida-designer#4]
**Describe the bug**
The `hetida-designer-backend` in the `docker-compose.yml` file does not expose port 8080.

**To Reproduce**
Follow the recommended [getting started instructions](https://github.com/hetida/hetida-designer#gs-docker-compose) and just run "docker-compose -d up". Going to `http://localhost` you'll get the generic message "an error occured", in the connection logs you'll see that the browser failed to connect to `localhost:8080`.

**Expected behavior**
Instead of the error message you should see your workflows.

**Screenshots**
(not applicable)

**Environment (please complete the following information):**
 - Runtime Environment: docker compose
 - Browser: firefox
 - hetida designer Version:   Release v0.6.2
 - Module: backend

**Related Issues**
(None)

**Suggested Fix**
Extend docker-compose.yml file to expose port 8080 in docker-compose.yml. 
For example:
```
  hetida-designer-backend:
[...]
    ports:
      - 8080:8080
```

**Comment by stewit** [comment]
Thanks, your detailed bug report is highly appreciated! I pushed a new release (0.6.3) which includes the suggested fix. Thanks again!
