### ISSUE TITLE
final docker command fails

### ISSUE THREAD

**Issue by deven-gqc** [hetida/hetida-designer#55]
Instructions to get hetida-designer up and running, fail on the last step.

Upon running the command, 
```
docker run --rm \
  -e "HETIDA_DESIGNER_BACKEND_API_URL=http://hetida-designer-backend:8090/api/" \
  --name htdruntime_deployment \
  --network hetida-designer-network \
  --entrypoint python hetida/designer-runtime -c 'from hetdesrun.exportimport.importing import import_all; import_all("./transformations/", update_component_code=False);'
```
This error message is produced 
![image](https://user-images.githubusercontent.com/86305049/174142494-ca52b95b-7242-4607-a470-79d746888e84.png)

and upon checking the code for `import_all()`.
![image](https://user-images.githubusercontent.com/86305049/174142636-451f2bce-e020-4eed-bd6d-813bafc35e53.png)
It does not have a `update_component_code` argument

Any suggested fixes for this? TIA!

**Comment by stewit** [comment]
Hello, thanks for opening this issue!

The update_component=False part is currently only present in the develop branch. Did you use that branch? The release branch Readme does not mention it at the moment.

Please use released versions (from the release branch) and also the documentation (aka Readme) from the release branch.

However I now see how you may have been lead to the develop branch Readme: Unfortunately github's "default" branch setting affects both what the "default" branch for pull requests is and what branch is shown by default when opening the repository's website (https://github.com/hetida/hetida-designer). I will look into that and maybe I will set the default branch to be "release".

Hope that helps

Thanks again!

**Comment by stewit** [comment]
I have now set the default branch to "release". Closing this issue. Please reopen it, if further problems occur!
